#Features from credit_card_balance dataset

Этот блокнот создает признаки из набора данных credit_card_balance. Набор данных credit_card_balance содержит ежемесячные снимки баланса предыдущих кредитных карт, которые заявитель имеет в Home Credit.

In [ ]:
import numpy as np
import pandas as pd

# -----------------------------------------------------
from google.colab import drive

# -----------------------------------------------------
import zipfile
import time
import sys
import os
import gc

In [ ]:
# Сброс ограничений на число столбцов
pd.set_option("display.max_columns", None)

# Сброс ограничений на число строк до 400
pd.set_option("display.max_rows", 400)

In [ ]:
# Подключение Google Drive к текущей среде выполнения

drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
# Функция распаковки содержимого архива в указанную директорию

def extract_zip_file(zip_path, extract_path):
    """
    Распаковка содержимого архива в указанную директорию

    :param zip_path: Путь к архиву
    :param extract_path: Путь к директории, куда нужно распаковать содержимое архива
    """
    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall(extract_path)

In [ ]:
# Распаковка содержимого архива home-credit-default-risk в текущую директорию

zip_file = "/content/drive/My Drive/home-credit-default-risk.zip"
extract_path = "/content/"

extract_zip_file(zip_file, extract_path)

In [ ]:
# Распаковка содержимого архива 3 - Bureau_balance features в текущую директорию

zip_file = "/content/drive/My Drive/3 - Bureau_balance features.zip"
extract_path = "/content/"

extract_zip_file(zip_file, extract_path)

In [ ]:
# Чтение данных

application = pd.read_csv("/content/3 - Bureau_balance features/application.csv")

credit_card_balance = pd.read_csv("/content/home-credit-default-risk/credit_card_balance.csv")
homecredit_columns_description = pd.read_csv("/content/3 - Bureau_balance features/homecredit_columns_description.csv", encoding="ISO-8859-1")

In [ ]:
# Проверка

application.shape

(356255, 179)

In [ ]:
# Описание столбцов в credit_card_balance

description_application = homecredit_columns_description[homecredit_columns_description["Table"] == "credit_card_balance.csv"]
for index, row in description_application.iterrows():
    print(row["Row"], row["Description"])

credit_card_balance.head(20)

SK_ID_PREV  ID of previous credit in Home credit related to loan in our sample. (One loan in our sample can have 0,1,2 or more previous loans in Home Credit)
SK_ID_CURR ID of loan in our sample
MONTHS_BALANCE Month of balance relative to application date (-1 means the freshest balance date)
AMT_BALANCE Balance during the month of previous credit
AMT_CREDIT_LIMIT_ACTUAL Credit card limit during the month of the previous credit
AMT_DRAWINGS_ATM_CURRENT Amount drawing at ATM during the month of the previous credit
AMT_DRAWINGS_CURRENT Amount drawing during the month of the previous credit
AMT_DRAWINGS_OTHER_CURRENT Amount of other drawings during the month of the previous credit
AMT_DRAWINGS_POS_CURRENT Amount drawing or buying goods during the month of the previous credit
AMT_INST_MIN_REGULARITY Minimal installment for this month of the previous credit
AMT_PAYMENT_CURRENT How much did the client pay during the month on the previous credit
AMT_PAYMENT_TOTAL_CURRENT How much did the client pay during the month in total on the previous credit
AMT_RECEIVABLE_PRINCIPAL Amount receivable for principal on the previous credit
AMT_RECIVABLE Amount receivable on the previous credit
AMT_TOTAL_RECEIVABLE Total amount receivable on the previous credit
CNT_DRAWINGS_ATM_CURRENT Number of drawings at ATM during this month on the previous credit
CNT_DRAWINGS_CURRENT Number of drawings during this month on the previous credit
CNT_DRAWINGS_OTHER_CURRENT Number of other drawings during this month on the previous credit
CNT_DRAWINGS_POS_CURRENT Number of drawings for goods during this month on the previous credit
CNT_INSTALMENT_MATURE_CUM Number of paid installments on the previous credit
NAME_CONTRACT_STATUS Contract status (active signed,...) on the previous credit
SK_DPD DPD (Days past due) during the month on the previous credit
SK_DPD_DEF DPD (Days past due) during the month with tolerance (debts with low loan amounts are ignored) of the previous credit

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.500,0.0,877.500,1700.325,1800.000,1800.000,0.000,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.000,0.0,0.000,2250.000,2250.000,2250.000,60175.080,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.000,0.0,0.000,2250.000,2250.000,2250.000,26926.425,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.000,0.0,0.000,11795.760,11925.000,11925.000,224949.285,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.000,0.0,11547.000,22924.890,27000.000,27000.000,443044.395,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
5,2646502,380010,-7,82903.815,270000,0.0,0.000,0.0,0.000,4449.105,3825.000,3825.000,80519.040,82773.315,82773.315,0.0,0,0.0,0.0,2.0,Active,7,0
6,1079071,171320,-6,353451.645,585000,67500.0,67500.000,0.0,0.000,14684.175,15750.000,15750.000,345433.860,351881.145,351881.145,1.0,1,0.0,0.0,6.0,Active,0,0
7,2095912,118650,-7,47962.125,45000,45000.0,45000.000,0.0,0.000,0.000,264.690,0.000,44735.310,47962.125,47962.125,1.0,1,0.0,0.0,51.0,Active,0,0
8,2181852,367360,-4,291543.075,292500,90000.0,289339.425,0.0,199339.425,130.500,4093.515,4093.515,285376.410,286831.575,286831.575,3.0,8,0.0,5.0,3.0,Active,0,0
9,1235299,203885,-5,201261.195,225000,76500.0,111026.700,0.0,34526.700,6338.340,45000.000,45000.000,192793.275,197224.695,197224.695,3.0,9,0.0,6.0,38.0,Active,0,0
10,1108284,209660,-7,102076.560,180000,92250.0,92250.000,0.0,0.000,0.000,4500.000,4500.000,92237.355,94224.060,94224.060,5.0,5,0.0,0.0,0.0,Active,0,0
11,2740914,340339,-1,131669.145,225000,10800.0,10800.000,0.0,0.000,6000.480,6322.500,6322.500,121430.700,127891.935,127891.935,2.0,2,0.0,0.0,6.0,Active,0,0
12,1985699,302517,-4,1427.265,135000,4500.0,101304.720,0.0,96804.720,3023.955,85500.000,85500.000,0.000,0.000,0.000,1.0,30,0.0,29.0,27.0,Active,0,0
13,1441883,171537,-5,0.000,270000,0.0,0.000,0.0,0.000,12218.490,2607.795,1448.640,0.000,0.000,0.000,0.0,0,0.0,0.0,2.0,Active,0,0
14,1864742,303581,-1,0.000,45000,0.0,0.000,0.0,0.000,0.000,2.295,0.000,0.000,0.000,0.000,0.0,0,0.0,0.0,59.0,Active,0,0
15,2037377,289902,-1,131294.340,135000,0.0,0.000,0.0,0.000,6774.660,6975.000,6975.000,128518.020,131294.340,131294.340,0.0,0,0.0,0.0,11.0,Active,0,0
16,1816636,255981,-6,72899.955,450000,67500.0,67500.000,0.0,0.000,2457.720,25200.000,25200.000,68954.805,71554.455,71554.455,1.0,1,0.0,0.0,42.0,Active,0,0
17,1039039,276642,-6,0.000,67500,0.0,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0,0.0,0.0,33.0,Completed,0,0
18,2016842,302450,-3,0.000,0,0.0,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0,0.0,0.0,2.0,Completed,0,0
19,1189095,231608,-4,452774.700,450000,9000.0,9000.000,0.0,0.000,22916.475,27000.000,27000.000,440329.050,451429.200,451429.200,1.0,1,0.0,0.0,22.0,Active,0,0

In [ ]:
# Извлечение признаков из credit_card_balance

# Создание пустых списков для каждого нового признака
nb_cc_home_credit_list = []
nb_cc_acive_home_credit_list = []
last_month_balance_list = []
last_3months_avg_balance_list = []
last_6months_avg_balance_list = []
last_12months_avg_balance_list = []
avg_balance_list = []
ratio_last_12months_balance_list = []
ratio_last_balance_income_list = []
cc_current_limit_list = []
cc_12months_limit_list = []
ratio_current_balance_limit_list = []
ratio_12months_balance_limit_list = []
last_3months_avg_drawings_list = []
last_12months_avg_drawings_list = []
avg_drawings_list = []
ratio_3_12months_avg_drawings_list = []
fr_ATM_drawings_12m_list = []
fr_goods_drawings_12m_list = []
fr_other_drawings_12m_list = []
min_installment_3months_list = []
min_installment_12months_list = []
fr_months_insufficient_payments_12m_list = []
fr_months_insufficient_payments_list = []
ratio_payments_installment_nodraw_12m_list = []
ratio_payments_installment_nodraw_list = []
principal_over_total_list = []
fr_min_installment_income_list = []
fr_drawings_income_list = []

counter = 0
lenght = len(application)
for index, row in application.iterrows():
    counter += 1
    sys.stdout.write('\r'+"Progress:"+str(round(counter/lenght*100,1))+"%")
    
    nb_cc_home_credit = 0
    nb_cc_acive_home_credit = 0
    last_month_balance = 0
    last_3months_avg_balance = 0
    last_6months_avg_balance = 0
    last_12months_avg_balance = 0
    avg_balance = 0
    ratio_last_12months_balance = np.NaN
    ratio_last_balance_income = np.NaN
    cc_current_limit = 0
    cc_12months_limit = 0
    ratio_current_balance_limit = np.NaN
    ratio_12months_balance_limit = np.NaN
    last_3months_avg_drawings = 0
    last_12months_avg_drawings = 0
    avg_drawings = 0
    ratio_3_12months_avg_drawings = np.NaN
    fr_ATM_drawings_12m = np.NaN
    fr_goods_drawings_12m = np.NaN
    fr_other_drawings_12m = np.NaN
    min_installment_3months = 0
    min_installment_12months = 0
    fr_months_insufficient_payments_12m = np.NaN
    fr_months_insufficient_payments = np.NaN
    ratio_payments_installment_nodraw_12m = np.NaN
    ratio_payments_installment_nodraw = np.NaN
    principal_over_total = np.NaN
    fr_min_installment_income = np.NaN
    fr_drawings_income = np.NaN
    
    df = credit_card_balance[credit_card_balance["SK_ID_CURR"] == row["SK_ID_CURR"]].sort_values(by="MONTHS_BALANCE", ascending = False)
    if len(df) > 0:
        unique_credit = df["SK_ID_PREV"].unique()
        # Количество прошлых кредитов по кредитной карте
        nb_cc_home_credit = len(unique_credit)
        
        # Для активных кредитов по кредитным картам
        tmp = df[df["NAME_CONTRACT_STATUS"] == "Active"]
        # Количество активных кредитов по кредитной карте
        nb_cc_acive_home_credit = len(tmp["SK_ID_PREV"].unique())
        df_1m = tmp.iloc[0:nb_cc_acive_home_credit]
        df_3m = tmp.iloc[0:nb_cc_acive_home_credit*3]
        df_6m = tmp.iloc[0:nb_cc_acive_home_credit*6]
        df_12m = tmp.iloc[0:nb_cc_acive_home_credit*12]
        # Сумма текущего баланса кредитной карты
        last_month_balance = df_1m["AMT_BALANCE"].mean()*nb_cc_acive_home_credit
        # Средняя сумма остатка на кредитной карте за последние 3 месяца
        last_3months_avg_balance = df_3m["AMT_BALANCE"].mean()*nb_cc_acive_home_credit
        # Средняя сумма остатка на кредитной карте за последние 6 месяцев
        last_6months_avg_balance = df_6m["AMT_BALANCE"].mean()*nb_cc_acive_home_credit
        # Средняя сумма остатка на кредитной карте за последние 12 месяцев
        last_12months_avg_balance = tmp.iloc[0:nb_cc_acive_home_credit*12]["AMT_BALANCE"].mean()*nb_cc_acive_home_credit
        # Средняя сумма остатка на кредитной карте по сравнению с кредитом
        avg_balance = tmp["AMT_BALANCE"].mean()*nb_cc_acive_home_credit
        # Соотношение остатка за последний месяц за последние 12 месяцев
        if last_12months_avg_balance > 0:
            ratio_last_12months_balance = last_month_balance / last_12months_avg_balance
        # Отношение остатка за последний месяц к общему доходу
        if row["AMT_INCOME_TOTAL"] > 0:
            ratio_last_balance_income = last_month_balance / row["AMT_INCOME_TOTAL"]
        # Сумма лимита кредитной карты
        cc_current_limit = df_1m["AMT_CREDIT_LIMIT_ACTUAL"].mean()
        # Средний лимит по кредитной карте за последние 12 месяцев
        cc_12months_limit = df_12m["AMT_CREDIT_LIMIT_ACTUAL"].mean()*nb_cc_acive_home_credit
        # Коэффициент ограничения текущего баланса
        if cc_current_limit > 0:
            ratio_current_balance_limit = last_month_balance / cc_current_limit
        # Средний коэффициент ограничения баланса за 12 месяцев
        if cc_12months_limit > 0:
            ratio_12months_balance_limit = last_12months_avg_balance / cc_12months_limit
        # Среднее количество заимствований за последние 3 месяца
        last_3months_avg_drawings = df_3m["AMT_DRAWINGS_CURRENT"].mean()*nb_cc_acive_home_credit
        # Среднее количество заимствований за последние 12 месяцев
        last_12months_avg_drawings = df_12m["AMT_DRAWINGS_CURRENT"].mean()*nb_cc_acive_home_credit
        # Среднее количество заимствований по сравнению с кредитом
        avg_drawings = tmp["AMT_DRAWINGS_CURRENT"].mean()*nb_cc_acive_home_credit
        # Соотношение средних заимствований за 3 месяца к 12 месяцам
        if last_12months_avg_drawings > 0:
            ratio_3_12months_avg_drawings = last_3months_avg_drawings / last_12months_avg_drawings
        # Доля заимствований банкоматов за последние 12 месяцев
            fr_ATM_drawings_12m = df_12m["AMT_DRAWINGS_ATM_CURRENT"].mean()*nb_cc_acive_home_credit / last_12months_avg_drawings
        # Процентные ставки за покупку товаров за последние 12 месяцев
            fr_goods_drawings_12m = df_12m["AMT_DRAWINGS_POS_CURRENT"].mean()*nb_cc_acive_home_credit / last_12months_avg_drawings
        # Доля других заимствований за последние 12 месяцев
            fr_other_drawings_12m = df_12m["AMT_DRAWINGS_OTHER_CURRENT"].mean()*nb_cc_acive_home_credit / last_12months_avg_drawings
        # Средний минимальный взнос за последние 3 месяца
        min_installment_3months = df_3m["AMT_INST_MIN_REGULARITY"].mean()*nb_cc_acive_home_credit
        # Средний минимальный взнос за последние 12 месяцев
        min_installment_12months = df_12m["AMT_INST_MIN_REGULARITY"].mean()*nb_cc_acive_home_credit
        # Соотношение между средним минимальным взносом за последние 3 месяца и доходом
        if row["AMT_INCOME_TOTAL"] > 0:
            fr_min_installment_income = min_installment_3months / row["AMT_INCOME_TOTAL"]
        # Соотношение между использованием кредитных карт и доходом за последние 12 месяцев
            fr_drawings_income = last_12months_avg_drawings / row["AMT_INCOME_TOTAL"] * 12
        # Доля месяцев с оплатой ниже минимального взноса за последние 12 месяцев
        if len(df_12m) > 0: 
            fr_months_insufficient_payments_12m = len(df_12m[df_12m["AMT_INST_MIN_REGULARITY"] > df_12m["AMT_PAYMENT_CURRENT"]]) / len(df_12m)
        # Доля месяцев с оплатой ниже минимального взноса по кредиту
        fr_months_insufficient_payments = len(df[df["AMT_INST_MIN_REGULARITY"] > df["AMT_PAYMENT_CURRENT"]]) / len(df)
        # Среднее соотношение между платежами и минимальным взносом за месяцы без просрочек в течение 12 месяцев
        if df_12m[df_12m["AMT_DRAWINGS_CURRENT"] == 0]["AMT_INST_MIN_REGULARITY"].mean() > 0:
            ratio_payments_installment_nodraw_12m = df_12m[df_12m["AMT_DRAWINGS_CURRENT"] == 0]["AMT_PAYMENT_CURRENT"].mean() / df_12m[df_12m["AMT_DRAWINGS_CURRENT"] == 0]["AMT_INST_MIN_REGULARITY"].mean()
        # Среднее соотношение между платежами и минимальным взносом в течение нескольких месяцев без перерасчета кредита
        if df[df["AMT_DRAWINGS_CURRENT"] == 0]["AMT_INST_MIN_REGULARITY"].mean() > 0:
            ratio_payments_installment_nodraw = df[df["AMT_DRAWINGS_CURRENT"] == 0]["AMT_PAYMENT_CURRENT"].mean() / df[df["AMT_DRAWINGS_CURRENT"] == 0]["AMT_INST_MIN_REGULARITY"].mean()
        # Сумма основного долга превышает общую сумму задолженности
        if df_1m["AMT_TOTAL_RECEIVABLE"].sum() > 0:
            principal_over_total = df_1m["AMT_RECEIVABLE_PRINCIPAL"].sum()/df_1m["AMT_TOTAL_RECEIVABLE"].sum()

    nb_cc_home_credit_list.append(nb_cc_home_credit)
    nb_cc_acive_home_credit_list.append(nb_cc_acive_home_credit)
    last_month_balance_list.append(last_month_balance)
    last_3months_avg_balance_list.append(last_3months_avg_balance)
    last_6months_avg_balance_list.append(last_6months_avg_balance)
    last_12months_avg_balance_list.append(last_12months_avg_balance)
    avg_balance_list.append(avg_balance)
    ratio_last_12months_balance_list.append(ratio_last_12months_balance)
    ratio_last_balance_income_list.append(ratio_last_balance_income)
    cc_current_limit_list.append(cc_current_limit)
    cc_12months_limit_list.append(cc_12months_limit)
    ratio_current_balance_limit_list.append(ratio_current_balance_limit)
    ratio_12months_balance_limit_list.append(ratio_12months_balance_limit)
    last_3months_avg_drawings_list.append(last_3months_avg_drawings)
    last_12months_avg_drawings_list.append(last_12months_avg_drawings)
    avg_drawings_list.append(avg_drawings)
    ratio_3_12months_avg_drawings_list.append(ratio_3_12months_avg_drawings)
    fr_ATM_drawings_12m_list.append(fr_ATM_drawings_12m)
    fr_goods_drawings_12m_list.append(fr_goods_drawings_12m)
    fr_other_drawings_12m_list.append(fr_other_drawings_12m)
    min_installment_3months_list.append(min_installment_3months)
    min_installment_12months_list.append(min_installment_12months)
    fr_months_insufficient_payments_12m_list.append(fr_months_insufficient_payments_12m)
    fr_months_insufficient_payments_list.append(fr_months_insufficient_payments)
    ratio_payments_installment_nodraw_12m_list.append(ratio_payments_installment_nodraw_12m)
    ratio_payments_installment_nodraw_list.append(ratio_payments_installment_nodraw)
    principal_over_total_list.append(principal_over_total)
    fr_min_installment_income_list.append(fr_min_installment_income)
    fr_drawings_income_list.append(fr_drawings_income)

Progress:100.0%

In [ ]:
# Функция для отображения описания выбранного признака

def add_description(table, row, description):
    list_description = [np.NaN, table, row, description, np.NaN]
    homecredit_columns_description.loc[len(homecredit_columns_description)] = list_description
    return homecredit_columns_description

In [ ]:
# Создание новых признаков из credit_card_balance

application["nb_cc_home_credit_list"] = nb_cc_home_credit_list
add_description("credit_card_balance.csv", "nb_cc_home_credit_list", "Number of past credit card credits")

application["nb_cc_acive_home_credit_list"] = nb_cc_acive_home_credit_list
add_description("credit_card_balance.csv", "nb_cc_acive_home_credit_list", "Number of active credit card credits")

application["last_month_balance_list"] = last_month_balance_list
add_description("credit_card_balance.csv", "last_month_balance_list", "Sum of current credit card balance")

application["last_3months_avg_balance_list"] = last_3months_avg_balance_list
add_description("credit_card_balance.csv", "last_3months_avg_balance_list", "Average sum of credit card balance over last 3 months")

application["last_6months_avg_balance_list"] = last_6months_avg_balance_list
add_description("credit_card_balance.csv", "last_6months_avg_balance_list", "Average sum of credit card balance over last 6 months")

application["last_12months_avg_balance_list"] = last_12months_avg_balance_list
add_description("credit_card_balance.csv", "last_12months_avg_balance_list", "Average sum of credit card balance over last 12 months")

application["avg_balance_list"] = avg_balance_list
add_description("credit_card_balance.csv", "avg_balance_list", "Average sum of credit card balance over credit")

application["ratio_last_12months_balance_list"] = ratio_last_12months_balance_list
add_description("credit_card_balance.csv", "ratio_last_12months_balance_list", "Ratio of last month balance over last 12 months")

application["ratio_last_balance_income_list"] = ratio_last_balance_income_list
add_description("credit_card_balance.csv", "ratio_last_balance_income_list", "Ratio of last month balance over total income")

application["cc_current_limit_list"] = cc_current_limit_list
add_description("credit_card_balance.csv", "cc_current_limit_list", "Sum credit card limit")

application["cc_12months_limit_list"] = cc_12months_limit_list
add_description("credit_card_balance.csv", "cc_12months_limit_list", "Average credit card limit over last 12 months")

application["ratio_current_balance_limit_list"] = ratio_current_balance_limit_list
add_description("credit_card_balance.csv", "ratio_current_balance_limit_list", "Current balance limit ratio")

application["ratio_12months_balance_limit_list"] = ratio_12months_balance_limit_list
add_description("credit_card_balance.csv", "ratio_12months_balance_limit_list", "Average 12months balance limit ratio")

application["last_3months_avg_drawings_list"] = last_3months_avg_drawings_list
add_description("credit_card_balance.csv", "last_3months_avg_drawings_list", "Average drawings over last 3 months")

application["last_12months_avg_drawings_list"] = last_12months_avg_drawings_list
add_description("credit_card_balance.csv", "last_12months_avg_drawings_list", "Average drawings over last 12 months")

application["avg_drawings_list"] = avg_drawings_list
add_description("credit_card_balance.csv", "avg_drawings_list", "Average drawings over credit")

application["ratio_3_12months_avg_drawings_list"] = ratio_3_12months_avg_drawings_list
add_description("credit_card_balance.csv", "ratio_3_12months_avg_drawings_list", "Ratio 3 months to 12 months average drawings")

application["fr_ATM_drawings_12m_list"] = fr_ATM_drawings_12m_list
add_description("credit_card_balance.csv", "fr_ATM_drawings_12m_list", "Fraction ATM drawings over last 12 months")

application["fr_goods_drawings_12m_list"] = fr_goods_drawings_12m_list
add_description("credit_card_balance.csv", "fr_goods_drawings_12m_list", "Fraction drawings for buying goods over last 12 months")

application["fr_other_drawings_12m_list"] = fr_other_drawings_12m_list
add_description("credit_card_balance.csv", "fr_other_drawings_12m_list", "Fraction other drawings over last 12 months")

application["min_installment_3months_list"] = min_installment_3months_list
add_description("credit_card_balance.csv", "min_installment_3months_list", "Average minimum installment over last 3 months")

application["min_installment_12months_list"] = min_installment_12months_list
add_description("credit_card_balance.csv", "min_installment_12months_list", "Average minimum installment over last 12 months")

application["fr_months_insufficient_payments_12m_list"] = fr_months_insufficient_payments_12m_list
add_description("credit_card_balance.csv", "fr_months_insufficient_payments_12m_list", "Fraction of months with payment lower than minimum installment over last 12 months")

application["fr_months_insufficient_payments_list"] = fr_months_insufficient_payments_list
add_description("credit_card_balance.csv", "fr_months_insufficient_payments_list", "Fraction of months with payment lower than minimum installment over credit")

application["ratio_payments_installment_nodraw_12m_list"] = ratio_payments_installment_nodraw_12m_list
add_description("credit_card_balance.csv", "ratio_payments_installment_nodraw_12m_list", "Average ratio between payments and minimum installment for months without drawings over 12 months")

application["ratio_payments_installment_nodraw_list"] = ratio_payments_installment_nodraw_list
add_description("credit_card_balance.csv", "ratio_payments_installment_nodraw_list", "Average ratio between payments and minimum installment for months without drawings over credit")

application["principal_over_total_list"] = principal_over_total_list
add_description("credit_card_balance.csv", "principal_over_total_list", "Principal over total due")

application["fr_min_installment_income_list"] = fr_min_installment_income_list
add_description("credit_card_balance.csv", "fr_min_installment_income_list", "Ratio between average minimum installment over last 3 months and income")

application["fr_drawings_income_list"] = fr_drawings_income_list
add_description("credit_card_balance.csv", "fr_drawings_income_list", "Ratio between credit card drawings and income over last 12 months");

In [ ]:
# Проверка

application.shape

(356255, 208)

In [ ]:
# Сохранение application

application.to_csv("application.csv", index=False)

In [ ]:
# Сохранение homecredit_columns_description

homecredit_columns_description.to_csv("homecredit_columns_description.csv", index=False)